{% set name = "pylibdmtx" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NaturalHistoryMuseum/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 137b170597a15d26c40a37192821eaa2e69e8f666b115fcf68054f0bc35e35d6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pylibdmtx

about:
  home: https://github.com/NaturalHistoryMuseum/pylibdmtx
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Read and write Data Matrix barcodes from Python 2 and 3 using the libdmtx library.
  doc_url: https://github.com/NaturalHistoryMuseum/pylibdmtx
  dev_url: https://github.com/NaturalHistoryMuseum/pylibdmtx

extra:
  recipe-maintainers:
    - Ryan-Dmello
